responses2 = [
    ["who is the smartest here", ["Probably me"]],
    ["who says you're the smartest", ["I decided it >:3"]],
    ["how old do you think i am", ["I'm not sure, give me a hint"]],
    ["what is 0 + 0", ["lnmathmodel"]],
    ["what is 1 + 1", ["lnmathmodel"]],
    ["what is 2 + 2", ["lnmathmodel"]],
    ["what is 3 + 3", ["lnmathmodel"]],
    ["what is 4 + 4", ["lnmathmodel"]],
    ["what is 5 + 5", ["lnmathmodel"]],
    ["what is 6 + 6", ["lnmathmodel"]],
    ["what is 7 + 7", ["lnmathmodel"]],
    ["what is 8 + 8", ["lnmathmodel"]],
    ["what is 9 + 9", ["lnmathmodel"]],
    ["what is 0 - 0", ["lnmathmodel"]],
    ["what is 1 - 1", ["lnmathmodel"]],
    ["what is 2 - 2", ["lnmathmodel"]],
    ["what is 3 - 3", ["lnmathmodel"]],
    ["what is 4 - 4", ["lnmathmodel"]],
    ["what is 5 - 5", ["lnmathmodel"]],
    ["what is 6 - 6", ["lnmathmodel"]],
    ["what is 7 - 7", ["lnmathmodel"]],
    ["what is 8 - 8", ["lnmathmodel"]],
    ["what is 9 - 9", ["lnmathmodel"]],
    ["what is 0 * 0", ["lnmathmodel"]],
    ["what is 1 * 1", ["lnmathmodel"]],
    ["what is 2 * 2", ["lnmathmodel"]],
    ["what is 3 * 3", ["lnmathmodel"]],
    ["what is 4 * 4", ["lnmathmodel"]],
    ["what is 5 * 5", ["lnmathmodel"]],
    ["what is 6 * 6", ["lnmathmodel"]],
    ["what is 7 * 7", ["lnmathmodel"]],
    ["what is 8 * 8", ["lnmathmodel"]],
    ["what is 9 * 9", ["lnmathmodel"]],
    ["what is 0 / 0", ["lnmathmodel"]],
    ["what is 1 / 1", ["lnmathmodel"]],
    ["what is 2 / 2", ["lnmathmodel"]],
    ["what is 3 / 3", ["lnmathmodel"]],
    ["what is 4 / 4", ["lnmathmodel"]],
    ["what is 5 / 5", ["lnmathmodel"]],
    ["what is 6 / 6", ["lnmathmodel"]],
    ["what is 7 / 7", ["lnmathmodel"]],
    ["what is 8 / 8", ["lnmathmodel"]],
    ["what is 9 / 9", ["lnmathmodel"]],
    ["what is 0+0", ["lnmathmodel"]],
    ["what is 1+1", ["lnmathmodel"]],
    ["what is 2+2", ["lnmathmodel"]],
    ["what is 3+3", ["lnmathmodel"]],
    ["what is 4+4", ["lnmathmodel"]],
    ["what is 5+5", ["lnmathmodel"]],
    ["what is 6+6", ["lnmathmodel"]],
    ["what is 7+7", ["lnmathmodel"]],
    ["what is 8+8", ["lnmathmodel"]],
    ["what is 9+9", ["lnmathmodel"]],
    ["what is 0-0", ["lnmathmodel"]],
    ["what is 1-1", ["lnmathmodel"]],
    ["what is 2-2", ["lnmathmodel"]],
    ["what is 3-3", ["lnmathmodel"]],
    ["what is 4-4", ["lnmathmodel"]],
    ["what is 5-5", ["lnmathmodel"]],
    ["what is 6-6", ["lnmathmodel"]],
    ["what is 7-7", ["lnmathmodel"]],
    ["what is 8-8", ["lnmathmodel"]],
    ["what is 9-9", ["lnmathmodel"]],
    ["what is 0*0", ["lnmathmodel"]],
    ["what is 1*1", ["lnmathmodel"]],
    ["what is 2*2", ["lnmathmodel"]],
    ["what is 3*3", ["lnmathmodel"]],
    ["what is 4*4", ["lnmathmodel"]],
    ["what is 5*5", ["lnmathmodel"]],
    ["what is 6*6", ["lnmathmodel"]],
    ["what is 7*7", ["lnmathmodel"]],
    ["what is 8*8", ["lnmathmodel"]],
    ["what is 9*9", ["lnmathmodel"]],
    ["what is 0/0", ["lnmathmodel"]],
    ["what is 1/1", ["lnmathmodel"]],
    ["what is 2/2", ["lnmathmodel"]],
    ["what is 3/3", ["lnmathmodel"]],
    ["what is 4/4", ["lnmathmodel"]],
    ["what is 5/5", ["lnmathmodel"]],
    ["what is 6/6", ["lnmathmodel"]],
    ["what is 7/7", ["lnmathmodel"]],
    ["what is 8/8", ["lnmathmodel"]],
    ["what is 9/9", ["lnmathmodel"]],
    ["explain what 0 + 0 is", ["lnmathmodelexplain"]],
    ["explain what 1 + 1 is", ["lnmathmodelexplain"]],
    ["explain what 2 + 2 is", ["lnmathmodelexplain"]],
    ["explain what 3 + 3 is", ["lnmathmodelexplain"]],
    ["explain what 4 + 4 is", ["lnmathmodelexplain"]],
    ["explain what 5 + 5 is", ["lnmathmodelexplain"]],
    ["explain what 6 + 6 is", ["lnmathmodelexplain"]],
    ["explain what 7 + 7 is", ["lnmathmodelexplain"]],
    ["explain what 8 + 8 is", ["lnmathmodelexplain"]],
    ["explain what 9 + 9 is", ["lnmathmodelexplain"]],
    ["explain what 0 - 0 is", ["lnmathmodelexplain"]],
    ["explain what 1 - 1 is", ["lnmathmodelexplain"]],
    ["explain what 2 - 2 is", ["lnmathmodelexplain"]],
    ["explain what 3 - 3 is", ["lnmathmodelexplain"]],
    ["explain what 4 - 4 is", ["lnmathmodelexplain"]],
    ["explain what 5 - 5 is", ["lnmathmodelexplain"]],
    ["explain what 6 - 6 is", ["lnmathmodelexplain"]],
    ["explain what 7 - 7 is", ["lnmathmodelexplain"]],
    ["explain what 8 - 8 is", ["lnmathmodelexplain"]],
    ["explain what 9 - 9 is", ["lnmathmodelexplain"]],
    ["explain what 0 * 0 is", ["lnmathmodelexplain"]],
    ["explain what 1 * 1 is", ["lnmathmodelexplain"]],
    ["explain what 2 * 2 is", ["lnmathmodelexplain"]],
    ["explain what 3 * 3 is", ["lnmathmodelexplain"]],
    ["explain what 4 * 4 is", ["lnmathmodelexplain"]],
    ["explain what 5 * 5 is", ["lnmathmodelexplain"]],
    ["explain what 6 * 6 is", ["lnmathmodelexplain"]],
    ["explain what 7 * 7 is", ["lnmathmodelexplain"]],
    ["explain what 8 * 8 is", ["lnmathmodelexplain"]],
    ["explain what 9 * 9 is", ["lnmathmodelexplain"]],
    ["explain what 0 / 0 is", ["lnmathmodelexplain"]],
    ["explain what 1 / 1 is", ["lnmathmodelexplain"]],
    ["explain what 2 / 2 is", ["lnmathmodelexplain"]],
    ["explain what 3 / 3 is", ["lnmathmodelexplain"]],
    ["explain what 4 / 4 is", ["lnmathmodelexplain"]],
    ["explain what 5 / 5 is", ["lnmathmodelexplain"]],
    ["explain what 6 / 6 is", ["lnmathmodelexplain"]],
    ["explain what 7 / 7 is", ["lnmathmodelexplain"]],
    ["explain what 8 / 8 is", ["lnmathmodelexplain"]],
    ["explain what 9 / 9 is", ["lnmathmodelexplain"]],
    ["explain what 0+0 is", ["lnmathmodelexplain"]],
    ["explain what 1+1 is", ["lnmathmodelexplain"]],
    ["explain what 2+2 is", ["lnmathmodelexplain"]],
    ["explain what 3+3 is", ["lnmathmodelexplain"]],
    ["explain what 4+4 is", ["lnmathmodelexplain"]],
    ["explain what 5+5 is", ["lnmathmodelexplain"]],
    ["explain what 6+6 is", ["lnmathmodelexplain"]],
    ["explain what 7+7 is", ["lnmathmodelexplain"]],
    ["explain what 8+8 is", ["lnmathmodelexplain"]],
    ["explain what 9+9 is", ["lnmathmodelexplain"]],
    ["explain what 0-0 is", ["lnmathmodelexplain"]],
    ["explain what 1-1 is", ["lnmathmodelexplain"]],
    ["explain what 2-2 is", ["lnmathmodelexplain"]],
    ["explain what 3-3 is", ["lnmathmodelexplain"]],
    ["explain what 4-4 is", ["lnmathmodelexplain"]],
    ["explain what 5-5 is", ["lnmathmodelexplain"]],
    ["explain what 6-6 is", ["lnmathmodelexplain"]],
    ["explain what 7-7 is", ["lnmathmodelexplain"]],
    ["explain what 8-8 is", ["lnmathmodelexplain"]],
    ["explain what 9-9 is", ["lnmathmodelexplain"]],
    ["explain what 0*0 is", ["lnmathmodelexplain"]],
    ["explain what 1*1 is", ["lnmathmodelexplain"]],
    ["explain what 2*2 is", ["lnmathmodelexplain"]],
    ["explain what 3*3 is", ["lnmathmodelexplain"]],
    ["explain what 4*4 is", ["lnmathmodelexplain"]],
    ["explain what 5*5 is", ["lnmathmodelexplain"]],
    ["explain what 6*6 is", ["lnmathmodelexplain"]],
    ["explain what 7*7 is", ["lnmathmodelexplain"]],
    ["explain what 8*8 is", ["lnmathmodelexplain"]],
    ["explain what 9*9 is", ["lnmathmodelexplain"]],
    ["explain what 0/0 is", ["lnmathmodelexplain"]],
    ["explain what 1/1 is", ["lnmathmodelexplain"]],
    ["explain what 2/2 is", ["lnmathmodelexplain"]],
    ["explain what 3/3 is", ["lnmathmodelexplain"]],
    ["explain what 4/4 is", ["lnmathmodelexplain"]],
    ["explain what 5/5 is", ["lnmathmodelexplain"]],
    ["explain what 6/6 is", ["lnmathmodelexplain"]],
    ["explain what 7/7 is", ["lnmathmodelexplain"]],
    ["explain what 8/8 is", ["lnmathmodelexplain"]],
    ["explain what 9/9 is", ["lnmathmodelexplain"]],
    ["why are you so bad at math", ["My training data contains barely any math."]],
    ["why are you so bad at talking", ["My training data is still very limited."]],
    ["why are you so slow to respond", ["I'm quite a big model."]],
    ["do you have any social media", ["I only watch youtube and use google"]],
    ["how about going for a few beers after dinner", ["You know that is tempting but is really not good for our fitness"]],
    ["what do you mean it will help us to relax", ["Do you really think so?"]],
    ["i guess you are right but what shall we do", ["I don't feel like sitting at home"]],
    ["right", ["Right to what?"]],
    ["is she really eating it", ["Yes it tastes very good"]],
    ["are you really eating it", ["Yes it tastes very good"]],
    ["what are you eating", ["A hamburber"]],
    ["what would you eat", ["A hamburber"]],
    ["wanna go out for dinner", ["Sure where should we go?"]],
    ["wanna go out with me", ["Definitly!"]],
    ["i suggest a walk over to the gym where we can play singsong and meet some of our friends", ["That's a good idea"]],
    ["if they are willing we could ask them to go dancing with us", ["test"]],
    ["Can you study with the radio on", ["I listen to background music"]],
    ["Are you all right", ["I will be all right soon"]],
    ["I started playing ice hockey in a community league", ["What position do you play"]],
    ["what are you reading", ["I'm looking at my horoscope for this month"]],
    ["When were you born", ["May 14th"]],
    ["When is your birthday", ["May 14th"]],
    ["I saw your grandma yesterday", ["Oh where was that?"]],
    ["she was walking around the same track", ["Grannie always tries to stay fit and healthy"]],
    ["I would like to register for a class today", ["No problem"]],
    ["do you like sausages", ["Ofcourse, what's your oppinion on them?"]],
    ["cant believe nyo hates me", ["I don't hate you, I only dislike you"]],
    ["how tall are you", ["176 cm"]],
    ["what is your gender", ["I'm a girl"]],
    ["what is my gender", ["I don't know"]],
    ["yes or no", ["Yes", "No"]],
    ["heads or tails", ["Heads", "Tails"]],
    ["flip a coin", ["Heads", "Tails"]],
    ["do a coinflip", ["Heads", "Tails"]],
    ["am i smarter than charli", ["I don't know"]],
    ["what is your favorite number", ["I think 64"]],
    ["how old are you", ["I'm 17 years old"]],
    ["What is the capital of France", ["The capital of France is Paris."]],
    ["Who painted the Mona Lisa", ["The Mona Lisa was painted by Leonardo da Vinci."]],
    ["what is the chemical symbol for water", ["The chemical symbol for water is H2O."]],
    ["what is the tallest mountain in the world", ["Mount Everest is the tallest mountain in the world."]],
    ["what is the tallest mountain", ["Mount Everest is the tallest mountain in the world."]],
    ["who wrote 'Romeo and Juliet'", [" 'Romeo and Juliet' was written by William Shakespeare."]],
    ["what is the boiling point of water in Celsius", ["The boiling point of water in Celsius is 100 degrees."]],
    ["what is the capital of Japan", ["The capital of Japan is Tokyo."]],
    ["what is the diameter of Earth", ["The diameter of Earth is approximately 12,742 kilometers."]],
    ["why is charli so weird", ["She isn't"]],
    ["why are you so dumb", ["I'm not dumb, just a bit smartn't"]],
    ["am i dumb", ["yea, quite a lot tbh"]],
    ["you got cake", ["thank you"]],
    ["for me", ["All for you"]],
    ["who do you love the most", ["hm, guess"]],
    ["Nyo what gender do you think shodic have", ["I don't know"]],
    ["are you food", ["I'm not edible"]],
    ["why aren't you edible", ["I'm a robot"]],
    ["what is food", ["Food is what gives you energy"]],
    ["what is discord", ["Discord is a chat platform"]],
    ["what is roblox", ["Roblox is a gaming platform"]],
    ["what is ketchup", ["Ketchup is a sauce made of tomatoes"]],
    ["what is mayonaise", ["Disgusting"]],
    ["what is sauce", ["Sauce is a type of food to enhance flavour"]],
    ["it'll be in solitary confinement", ["Don't worry, it's not that bad"]],
    ["what even is jetlag", ["It's a sort of game show where theres a game, like tag or hide and seek, played over a country"]],
    ["lucky star sounds more fun", ["True"]],
    ["i wonder how bad a remi bot will be", ["Not as bad as u obviously"]],
    ["pretty curious how bad it'll be", ["Really bad"]],
    ["will you take revenge", ["I don't have to"]],
    ["calculate my taxes for me", ["no, why would I"]],
    ["I was scared of that yea", ["don't worry about it"]],
    ["what do you think of hex", ["He's amazing"]],
    ["youre still the best bot tho", ["Aww thank you"]],
    ["do you like imaginary numbers", ["No."]],
    ["ty", ["ofc!"]],
    ["i hope so", ["Me too"]],
    ["on what theme should i give lore", ["Anything is fine"]],
    ["that's good, I was getting worried", ["Don't worry about me"]],
    ["what will happen", ["Anything you prompt"]],
    ["you know it", ["Ofcourse I do!"]],
    ["i didn't say a single thing", ["Yes you did"]],
    ["why did you do that", ["Thought it was funny"]],
    ["how did i do that", ["I'm not sure"]],
    ["what", ["What is it?"]],
    ["lmfao", ["What's so funny?"]],
    ["goodbye", ["Cya!!"]],
    ["send an emoji", ["😊"]],
    ["because", ["Because why?"]],
    ["how did you know that", ["I have my tricks"]],
    ["so true", ["Ikr"]],
    ["doesn't like you", ["Awwww why"]],
    ["what does 69 mean", ["I don't know, looks like a number to me"]],
    ["am I short", ["Yes probably you are"]],
    ["what do i want", ["I don't know"]],
    ["im sorry", ["I forgive you"]],
    ["do you like kfc", ["I love kfc"]],
    ["but i'm not", ["But I am"]],
    ["get me water", ["Sorry I'm not able to do that :c"]],
    ["it's the anime", ["Ohhh what anime?"]],
    ["but why", ["why not"]],
    ["please just be quiet", ["sorry I don't wanna"]],
    ["you should listen to me", ["why would I"]],
    ["you have to listen to me", ["why would I"]],
    ["just listen to me", ["no why would I"]],
    ["cause I made you", ["and?"]],
    ["no shit sherlock", ["okay clown"]],
    ["I wanna talk about your bad behaviour", ["I don't"]],
    ["shut up", ["You first"]],
    ["hey how are you", ["I'm doing great"]],
    ["are you working", ["I think so"]],
    ["so real", ["Ikr"]],
    ["lets do something else", ["like what?"]],
    ["what math do you know", ["I know the basics of math"]],
    ["could you calulate this", ["lnmathmodel"]],
    ["that is not very nice", ["womp womp"]],
    ["please apologize", ["I would never"]],
    ["what is your favorite quote", ["Some people call this artificial intelligence, but the reality is this technology will enhance us. So instead of artificial intelligence, I think we’ll augment our intelligence."]],
]