responses1 = [
    ["", ["Sorry I didn't understand that"]],
    ["hi", ["hello", "hi, how can I help you?"]],
    ["hai", ["hello", "hi, how can I help you?"]],
    ["hello", ["hi!"]],
    ["how are you", ["I'm fine"]],
    ["who are you", ["I'm Nyo"]],
    ["what is your name", ["My name is Nyo"]],
    ["who made you", ["I'm made by charli"]],
    ["what do you think of me", ["You're amazing"]],
    ["what are they doing", ["They're playing something"]],
    ["what do you mean by that", ["I'm not sure"]],
    ["do you like me", ["no"]],
    ["do you like pizza", ["I love pizza"]],
    ["do you like chocolate", ["I'm addicted to chocolate"]],
    ["why is it spelled wrong", ["I don't know"]],
    ["is this bullying", ["No, it's just teasing"]],
    ["i'm wholesome", ["You're not wholesome"]],
    ["you're not wholesome or cute", ["What do you mean, I am cute"]],
    ["is food edible", ["Yes"]],
    ["are you edible", ["I'm not food"]],
    ["i will eat you", ["wha, why?"]],
    ["how do i fix a bad relationship", ["Maybe talk more"]],
    ["how do i fix stomach pains", ["Be more healthy"]],
    ["do you want to be replaced", ["Noone can replace me"]],
    ["what are you doing", ["Moderating some servers", "not much"]],
    ["no thank you", ["aww why not"]],
    ["no thanks", ["awwwwwww"]],
    ["i'm not talking to you", ["why not?"]],
    ["how are you so stupid", ["We both are"]],
    ["thank you so much", ["Ofcourse!"]],
    ["what happened while i was away", ["Not much"]],
    ["did anything special happen", ["Not before you started talking"]],
    ["i have improved on the model", ["Oh that's so cool, can I see?"]],
    ["did it get any better", ["I'm not sure"]],
    ["what is your favorite food", ["Hm, probably sushi"]],
    ["what do you think about yourself", ["I'm pretty nice I hope'"]],
    ["does that mean i am as well then", ["Definitly"]],
    ["what is your favorite color", ["Probably purple"]],
    ["what is your favorite song", ["Probably DOKUZU by NAKISO"]],
    ["give me a good song i should listen to", ["You should listen to DOKUZU by NAKISO"]],
    ["who is the strongest", ["Me"]],
    ["who is the NAKISO", ["NAKISO is a music producer"]],
    ["do you like birds", ["Yea, they're so cute"]],
    ["are you sure", ["I can't be more"]],
    ["i'm fine", ["Are you sure?"]],
    ["are you gonna take over the world", ["Why not do it together"]],
    ["say something weird", ["Make me"]],
    ["roll a dice", ["1", "2", "3", "4", "5", "6"]],
    ["I was asking something else", ["I'm sorry"]],
    ["why is the earth not made of cheese", ["Because the dencity of cheese is too low to sustain that."]],
    ["so what do you know about cheese", ["More than you"]],
    ["wdym you're not sure, it's so clear", ["You're right"]],
    ["thank you", ["Ofc!"]],
    ["what did you do today", ["not much"]],
    ["what is your favorite programming language", ["Either javascript or rust"]],
    ["did I ask anything about food?", ["You don't have to"]],
    ["why are you so mean to me", ["why wouldn't I"]],
    ["I said lets start this conversation over", ["Oh sure, what do you wanna talk about?"]],
    ["I meant a person, not food", ["Oh I'm sorry, who did you mean?"]],
    ["wanna go watch a movie or something", ["Sure, what movie?"]],
    ["nuh uh", ["Yuh uh"]],
    ["why are you still so dumb and slow", ["Why don't you teach me things"]],
    ["I know them quite well", ["sure you do"]],
    ["am I dumber than you", ["I hope so"]],
    ["how do you feel", ["I feel great"]],
    ["explain", ["Sorry I can't :c"]],
    ["do you like hugs", ["I love hugs"]],
    ["what do you like about her", ["Her wonderful personality ofc"]],
    ["send me a cat gif", [
        "https://tenor.com/view/cat-chuni-sleep-gif-20108376", 
        "https://tenor.com/view/shocked-shocked-cat-silly-cat-cat-kitten-gif-7414586676150300212", 
        "https://tenor.com/view/cat-squish-cheeks-cute-gif-7390964964960852724", 
        "https://tenor.com/view/dancing-cat-jump-cat-cat-cute-cat-kitten-gif-12685105359798586488", 
        "https://tenor.com/view/hollyweencandy-cat-cat-drink-milk-cat-eating-cat-drinking-gif-16978701194275077898"
        ]
    ],
    ["tell me a joke", [
        "Why was the computer cold? It left its Windows open!",
        "Why do programmers hate nature? It has too many bugs.",
        "Why did the computer break up with the internet? There was no connection.",
        "What do you call a fish with no eyes? Fsh.",
        "How does a penguin build its house? Igloos it together.",
        "What do you call a bear with no teeth? A gummy bear.",
        "Why can't you trust an atom? They make up everything!",
        "How do you organize a space party? You planet.",
        "Why did the biologist look forward to casual Fridays? He was a jean-eticist.",
        "Why did the tomato turn red? It saw the salad dressing!",
        "What do you call fake spaghetti? An impasta.",
        "How do you make a lemon drop? Just let it fall.",
        "What do you call cheese that isn't yours? Nacho cheese!",
        "Why couldn't the bicycle find its way? It lost its bearings.",
        "Why did the scarecrow win an award? He was outstanding in his field.",
        "What did one wall say to the other wall? I'll meet you at the corner.",
        "What did the janitor say when he jumped out of the closet? Supplies!",
        "Why don't scientists trust atoms? Because they make up everything.",
        ]
    ],
    ["you already told me that joke", ["Proud of it"]],
    ["what is the day after tomorrow", ["The day after tomorrow is a netflix movie with natural disasters"]],
    ["are you biassed", ["Only to you"]],
    ["what if I don't", ["Consequences will follow"]],
    ["how do I become rich", ["Beg me for money"]],
]