commands = [
    ["make a note for today", ["_noteToday_"]],
    ["make a note for tomorrow", ["_noteTomorrow_"]],
    ["make a note for yesterday", ["_noteYesterday_"]],
    ["make a note in 1 day", ["_noteInNumber_"]],
    ["make a note in 2 days", ["_noteInNumber_"]],
    ["make a note in 3 days", ["_noteInNumber_"]],
    ["make a note in 4 days", ["_noteInNumber_"]],
    ["make a note in 5 days", ["_noteInNumber_"]],
    ["make a note in 6 days", ["_noteInNumber_"]],
    ["make a note in 7 days", ["_noteInNumber_"]],
    ["make a note in 8 days", ["_noteInNumber_"]],
    ["make a note in 9 days", ["_noteInNumber_"]],
    ["make a note in 0 days", ["_noteInNumber_"]],
    ["make a note in 1 day ago", ["_noteInNumberAgo_"]],
    ["make a note in 2 days ago", ["_noteInNumberAgo_"]],
    ["make a note in 3 days ago", ["_noteInNumberAgo_"]],
    ["make a note in 4 days ago", ["_noteInNumberAgo_"]],
    ["make a note in 5 days ago", ["_noteInNumberAgo_"]],
    ["make a note in 6 days ago", ["_noteInNumberAgo_"]],
    ["make a note in 7 days ago", ["_noteInNumberAgo_"]],
    ["make a note in 8 days ago", ["_noteInNumberAgo_"]],
    ["make a note in 9 days ago", ["_noteInNumberAgo_"]],
    ["make a note in 0 days ago", ["_noteInNumberAgo_"]],
]